In [ ]:
import pandas as pd
df= pd.read_excel(r'/content/clustering.xlsx')

In [ ]:
contract_map = {
    "Month-to-Month": 0,
    "One Year": 1,
    "Two Year": 2
}

df["contract_length"] = df["contract"].map(contract_map)

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
import numpy as np

features = [
    "tenure_in_months",
    "monthly_charge",
    "number_of_referrals",
    "number_of_dependents",
    "contract_length"
]

X = df[features].copy()

# bỏ giá trị âm vô nghĩa (vd monthly_charge = -10)
X[X < 0] = np.nan

# fill missing
X = SimpleImputer(strategy="median").fit_transform(X)

# scale để các biến có trọng số công bằng
X_scaled = StandardScaler().fit_transform(X)

In [ ]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df["cluster"] = kmeans.fit_predict(X_scaled)

In [ ]:
import pandas as pd

churn_rate = pd.crosstab(
    df["cluster"],
    df["customer_status"],
    normalize="index"
) * 100

churn_rate

customer_status    Churned     Stayed
cluster
0                 2.471679  97.528321
1                53.877140  46.122860
2                11.317470  88.682530
3                 4.912664  95.087336

In [ ]:
df.groupby("cluster")[features].mean().round(2)

,tenure_in_months,monthly_charge,number_of_referrals,number_of_dependents,contract_length
cluster,,,,,
0,51.71,69.97,7.51,0.30,1.31
1,16.66,64.84,0.49,0.08,0.11
2,53.02,69.03,0.68,0.12,1.55
3,39.44,52.89,3.70,2.60,1.07